export default  class BackgroundUtil {

  static getBackgroundImage(weatherCondition: string): Resource {
    switch (weatherCondition.toLowerCase()) {
      case '晴':
        return $r('app.media.sunny_background');
      case '多云':
        return $r('app.media.default_background1');
      case '阴':
        return $r('app.media.overcast_background');
      case '雨':
      case '小雨':
      case '中雨':
      case '大雨':
        return $r('app.media.rainy_background');
      case '雪':
      case '小雪':
      case '中雪':
      case '大雪':
        return $r('app.media.snowy_background');
      default:
        return $r('app.media.default_background');
    }
  }
}

