
@Component
export default  struct SunRise {
  build() {
    // 太阳升落
    /*Row() {
      Text('06:01')
        .fontSize(14)
      Slider({
        value: this.sunriseProgress,
        min: 0,
        max: 100,
        style: SliderStyle.OutSet
      })
        .width('70%')
        .height(20)
        .blockColor(Color.Yellow)
        .trackThickness(10)
        .showSteps(false)
        .showTips(false)
        .trackColor(Color.White)
        .selectedColor('#ffd9d7d7')
      Text('19:39')
        .fontSize(14)
    }
    .width('100%')
    .justifyContent(FlexAlign.SpaceBetween)*/
  }
}